= Hawkular Android Client

This repository contains the source code for the Hawkular Android application.

== License

* http://www.apache.org/licenses/LICENSE-2.0.html[Apache Version 2.0]

== Building

ifdef::env-github[]
[link=https://travis-ci.org/hawkular/hawkular-android-client]
image:https://travis-ci.org/hawkular/hawkular-android-client.svg["Build Status", link="https://travis-ci.org/hawkular/hawkular-android-client"]
endif::[]

You will need JDK 1.7+ installed.
Gradle, Android SDK and all dependencies will be downloaded automatically.

=== Debug

-----
$ ./gradlew clean assembleDebug
-----

=== Release

-----
$ cp properties/signing.properties .
$ vi signing.properties

$ ./gradlew clean assembleRelease
-----

== Demo Server

Demo server is hosted at `http://livingontheedge.hawkular.org/`

To signin with android client use

host : `livingontheedge.hawkular.org`

port : by default 80, not needed to specify

username : `jdoe`

password : `password`

== Reading

There are some documents on the link:../../wiki[Wiki], including API overview, UI mockups
and instructions on running necessary servers for using the client in common and
push notifications specifically.

== Contributing

- When you decide you want to start coding for Hawkular Android Client, add
https://github.com/hawkular/hawkular-build-tools/tree/master/ide-configs/idea[settings.jar]
into android studio by following
https://www.jetbrains.com/help/idea/2016.3/exporting-and-importing-settings.html[guide of IntelliJ IDEA].

- Execute  `$ mvn license:format` before commit to correct license headers.

- Execute `$ mvn clean install` before sending PR to confirm your present code pass coding standards of Hawkular.
